name: Compile and Release PDF
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Nutné pro nahrávání do Releases
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
          # Použijeme akci, která v sobě má TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=build

      - name: Update Latest Release
        uses: andelf/generate-release-action@v1
        if: github.ref == 'refs/heads/main' # Spustí se jen při pushi do hlavní větve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: "Nejnovější verze kuchařky"
          body: "Toto PDF je automaticky generováno při každém pushi do větve main."
          files: build/main.pdf
